package com.recursion.problem;

/*
Problem Statement :
Given a string, write a method to return all its subsequences in an arraylist.
A string is a subsequence of a given String that is generated by deleting some character
of a given string without changing its order

Input : "abc"
Output : "", a, b, c, ab, bc, ac, abc
 */

import java.util.ArrayList;

public class _25_Sub_sequence_string_print
{
    public static void main(String[] args)
    {
        subSequence("abc", "");
    }


    public static void subSequence(String s, String currAns)
    {
        if(s.length() == 0)
        {
            System.out.print(currAns + ", ");
            return;
        }

        char curr = s.charAt(0);   // extract the 0th character
        String remaining = s.substring(1);

        subSequence(remaining, currAns+curr); //include current character
        subSequence(remaining, currAns); // doo not include current character
    }

}


